name: 'Node Versionize'
description: 'Bump the package.json version detail and create a git tag'
author: 'Winner-Timothy Bolorunduro'
inputs:
  bump-type:
    description: 'What part of the version to increment.'
    required: true
    default: 'patch'
  user-name:
    description: 'The user name to be used for commits and the tag. Defaults to the HEAD commit authors name.'
    required: false
    default: ''
  user-email:
    description: 'The user email to be used for commits and the tag. Defaults to the HEAD commit authors email.'
    required: false
    default: ''
  github-token:
    description: 'The Github token.'
    required: false
    default: ${{ github.token }}
  traverse-dirs:
    description: 'Whether or not to search sub-folders for the package.json file.'
    required: false
    default: 'false'
outputs:
  version:
    description: 'The new package version'
runs:
  using: 'node16'
  main: 'dist/index.js'
